models/__init__.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


def init_app(app):
    print(app.config["SQLALCHEMY_DATABASE_URI"])
    db.init_app(app)
    with app.app_context():
        db.create_all()

models/folios.py
from . import db



class Folio(db.Model):
    id = db.Column(
        db.BigInteger().with_variant(db.Integer, "sqlite"),
        primary_key=True,
        autoincrement=True,
    )

    name = db.Column(db.String)
    email = db.Column(db.String)

    biography = db.Column(db.String)
    education = db.Column(db.String)
    date_of_birth = db.Column(db.String)

models/users.py
from flask_login import UserMixin
from . import db


class User(db.Model, UserMixin):
    id = db.Column(
        db.BigInteger().with_variant(db.Integer, "sqlite"),
        primary_key=True,
        autoincrement=True,
    )
    password = db.Column(db.String, unique=True, nullable=False)
    email = db.Column(db.String)

    first_name = db.Column(db.String)
    last_name = db.Column(db.String)

forms/accounts.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms import validators


class LoginForm(FlaskForm):
    email = StringField(
        "name", validators=[validators.DataRequired(), validators.Length(min=3)]
    )
    password = StringField(
        "password",
        validators=[
            validators.DataRequired(),
            validators.Length(min=3, message="มากกว่า 3"),
        ],
    )


class RegisterForm(FlaskForm):
    email = StringField(
        "email", validators=[validators.DataRequired(), validators.Length(min=3)]
    )
    password = StringField(
        "password",
        validators=[
            validators.DataRequired(),
            validators.Length(min=3, message="มากกว่า 3"),
        ],
    )
    first_name = StringField("first_name", validators=[validators.DataRequired()])
    last_name = StringField("password", validators=[validators.DataRequired()])

forms/folios.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms import validators
from wtforms import widgets


class FolioForm(FlaskForm):
    email = StringField(
        "email", validators=[validators.DataRequired(), validators.Length(min=3)]
    )
    name = StringField("Name", validators=[validators.DataRequired()])
    biography = StringField("Biography", widget=widgets.TextArea())
    education = StringField("Education", widget=widgets.TextArea())
    date_of_birth = StringField("Birth Date", validators=[validators.DataRequired()])

main.py
from flask import Flask, render_template, redirect, url_for
from flask_login import LoginManager

from views import accounts
from views import folios
import models
from models import users

import os

login_manager = LoginManager()
login_manager.login_view = "accounts.login"


@login_manager.unauthorized_handler
def unauthorized():
    # do stuff
    # return "You don't have permission"
    print("You don't have permission")
    return redirect(url_for("accounts.login"))

app = Flask(__name__)

@login_manager.user_loader
def load_user(user_id):
    user = models.db.session.query(users.User).filter_by(id=user_id).first()
    return user

@app.route("/")
def index():
    return render_template("main/index.html")


if __name__ == "__main__":
    app.secret_key = "123456"  # import os // os.get_env['SECRET_KEY']
    login_manager.init_app(app)

    # app.config["SQLALCHEMY_DATABASE_URI"] = f"sqlite:///:memory"
    app.config["SQLALCHEMY_DATABASE_URI"] = f"sqlite:///{os.getcwd()}/db/project.db"
    models.init_app(app)

    app.register_blueprint(accounts.bp)
    app.register_blueprint(folios.bp)
    
    app.run(debug=True)

views/accounts.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_required, login_user, logout_user

from werkzeug.security import generate_password_hash, check_password_hash

import models
from models import users, folios
from forms import accounts as accounts_form


bp = Blueprint("accounts", __name__, url_prefix="/accounts")


@bp.route("/login")
def login():
    form = accounts_form.LoginForm()
    return render_template("/accounts/login.html",form=form)

@bp.route("/logout")
def logout():
    logout_user()
    return redirect("/")



@bp.route("/do-login", methods=["POST"])
def do_login():

    form = accounts_form.LoginForm()

    if not form.validate_on_submit():
        return redirect(url_for("accounts.login", **form.errors))

    user = (
        models.db.session.query(users.User)
        .filter_by(
            email=form.email.data,
        )
        .first()
    )

    if not user:
        return redirect(url_for("accounts.login", message="invalid login"))

    if not check_password_hash(user.password, form.password.data):
        return redirect(url_for("accounts.login", message="invalid password"))

    login_user(user)

    return redirect(url_for("accounts.dashboard"))

@bp.route("/register", methods=["GET", "POST"])
def register():
    form = accounts_form.RegisterForm()
    if not form.validate_on_submit():
        return render_template("/accounts/register.html", form=form)

    user = users.User()
    form.populate_obj(user)

    print(form.data)
    user.password = generate_password_hash(form.password.data, method="sha256")

    # db management
    models.db.session.add(user)
    models.db.session.commit()

    return redirect(url_for("accounts.login"))

@bp.route("/dashboard")
@login_required
def dashboard():
    folio_data = models.db.session.query(folios.Folio).all()
    return render_template("/accounts/dashboard.html", folio_data=folio_data)

views/folios.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_required, login_user, logout_user

from werkzeug.security import generate_password_hash, check_password_hash

from forms import folios as folios_form
import models
from models import folios

bp = Blueprint("folios", __name__, url_prefix="/folios")


@bp.route("/create", methods=["GET", "POST"])
def create():
    form = folios_form.FolioForm()
    if not form.validate_on_submit():
        return render_template("/folios/create.html", form=form)

    folio = folios.Folio()
    form.populate_obj(folio)

    models.db.session.add(folio)
    models.db.session.commit()

    return redirect(url_for("accounts.dashboard"))


@bp.route("/<folio_id>/update", methods=["GET", "POST"])
def update(folio_id):
    folio = (
        models.db.session.query(folios.Folio)
        .filter_by(
            id=folio_id,
        )
        .first()
    )

    form = folios_form.FolioForm(obj=folio)
    if not form.validate_on_submit():
        return render_template("/folios/create.html", form=form)

    form.populate_obj(folio)

    # models.db.session.update(folio)
    models.db.session.commit()

    return redirect(url_for("accounts.dashboard"))


@bp.route("/<folio_id>/delete")
@login_required
def delete(folio_id):
    folio = (
        models.db.session.query(folios.Folio)
        .filter_by(
            id=folio_id,
        )
        .first()
    )

    models.db.session.delete(folio)
    models.db.session.commit()

    return redirect(url_for("accounts.dashboard"))


@bp.route("/<folio_id>")
@login_required
def view(folio_id):
    folio = (
        models.db.session.query(folios.Folio)
        .filter_by(
            id=folio_id,
        )
        .first()
    )

    return render_template("/folios/view.html", folio=folio)

templates/accounts/dashboard.html
<!DOCTYPE html>
<html>
  <head>
    <title>Dashboard</title>
    <link rel="stylesheet" href="https://kit.fontawesome.com/eab4031eed.css" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/eab4031eed.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </head>
<style>
  #grad1 {
    position:relative;
    background-color:transparent ;
    color: rgb(0,255,255);
    text-align: center;
    width:50%;
    font-size: 2em;
    letter-spacing: 2vw;
    text-shadow: 2px 2px white;
    font-weight: 900;
    margin-bottom:0;
    height:50px;
    top:-8px;
    right:10vw;
  }
  .head-ui{
    padding:10px;
    position:relative;
    padding-right:7vw;
    padding-left:7vw;
    background-color:rgb(78,53,36);  
    box-shadow: 0 1px 3px 0 black;
  }
  .item{
    padding-top:10px;
    padding-bottom:10px;
    padding-right:3vw;
    padding-left:3vw;
    position:relative;
    text-align: center;
    font-size: 20px;
    color: white;
    text-decoration-line: none;
  }
  a:hover {
    background-color: rgb(160, 110, 73);
  }
  .bar{
    width:100%; 
    height:10vh;
    grid-template-columns: auto;
    display: grid;
    gap: 20px;
  }
  .bar-item{
    width:100%;
    position:relative;
    text-align: left;
    float:none;
    color: white;
    text-decoration-line: none;
    padding:20px;
  }
  .bar-item:hover{
    background-color: rgb(0, 191, 255);
  }
  .offcanvas-title:hover{
    color:rgb(0, 191, 255);
  }
  .center-con {
    display:flex; 
    justify-content: center; 
    align-item:center;
    margin-top:7px;
  }
</style>
<body style="background-image: url('/static/lorenzo-lanfranconi-mediterranean-gothic-o.jpg');">  

    <header>
      <div class="head-ui">
        <div class="offcanvas offcanvas-start" data-bs-scroll="true" tabindex="-1" id="offcanvasWithBothOptions" aria-labelledby="offcanvasWithBothOptionsLabel" 
          style="background-image: linear-gradient(to right, rgb(0,0,205) , rgb(0,255,255)); color: white;">
          <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="offcanvasWithBothOptionsLabel" data-bs-dismiss="offcanvas" aria-label="Close">
            <i class="fa-solid fa-bars" style="margin-right:1vw;"></i>MENU
            </h5>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
          </div>
          <div class="offcanvas-body" style="padding: 0;">
            <div class="bar">
              <a href="/" class="bar-item"><i class="fa-solid fa-house" style="margin-right:1vw;"></i>HOME</a>
              <a href="{{ url_for('accounts.dashboard') }}" class="bar-item"><i class="fa-solid fa-file" style="margin-right:1vw;"></i>DASHBOARD</a>
              <a href="{{ url_for('folios.create') }}" class="bar-item"><i class="fa-solid fa-file-circle-plus" style="margin-right:1vw;"></i>CREATE DASHBOARD</a>
              <a href="{{ url_for('accounts.logout') }}" class="bar-item"><i class="fa-solid fa-right-from-bracket" style="margin-right:1vw;"></i>LOGOUT</a>
              <p style="padding:10px;">Enjoy your folios.</p>
            </div> 
          </div>
        </div>
        <a class="item" data-bs-toggle="offcanvas" data-bs-target="#offcanvasWithBothOptions" aria-controls="offcanvasWithBothOptions"> 
          <i class="fa-solid fa-bars" style="margin-right:1vw;"></i>
          MENU
        </a>
        <div style="float: right; ">
          <a class="item"  href="{{ url_for('accounts.logout') }}"> <i class="fa-solid fa-right-from-bracket" style="margin-right:1vw;"></i>LOGOUT</a>
        </div>
        <h1 id="grad1" style="float: right; " >
          <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" class="bi bi-journal-bookmark-fill" viewBox="0 0 16 20" >
            <path fill-rule="evenodd" d="M6 1h6v7a.5.5 0 0 1-.757.429L9 7.083 6.757 8.43A.5.5 0 0 1 6 8V1z"/>
            <path d="M3 0h10a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2v-1h1v1a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H3a1 1 0 0 0-1 1v1H1V2a2 2 0 0 1 2-2z"/>
            <path d="M1 5v-.5a.5.5 0 0 1 1 0V5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0V8h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0v.5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1z"/>
          </svg>
          FOLIOS
        </h1>
        
      </div>

    </header>
    
    <div style=" margin:0 5vw; padding-top:1vw; background-color:rgb(240 248 255 / 0.7); height:93.2vh; padding:1vw 3vw;" >
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-5" style="border-bottom: 1px solid rgb(78,53,36); width:68vw; margin:0 8vw; ">
        <h1 class="h2" ><i class="fa-solid fa-clipboard-user" style="margin-right:1vw;"></i>Dashboard</h1>
      </div>
    <table class="table" >
      <thead style="margin-right:5vw; border-bottom: 1px solid rgb(78,53,36)">
        <tr style="margin-right:5vw;">
          <th scope="col" >#</th>
          <th scope="col" ><i class="fa-solid fa-user" style="margin-right:2px;"></i>Name</th>
          <th scope="col" ><i class="fa-solid fa-envelope"style="margin-right:2px;"></i>Email</th>
          <th scope="col" ><i class="fa-solid fa-address-book"style="margin-right:2px;"></i>Biography</th>
          <th scope="col" ><i class="fa-solid fa-user-graduate"style="margin-right:2px;"></i>Education</th>
          <th scope="col" ><i class="fa-solid fa-baby"style="margin-right:2px;"></i>Birth Date</th>
          <th scope="col" ><i class="fa-solid fa-screwdriver-wrench" style="margin-right:2px;"></i>Action</th>
        </tr>
      </thead>
      <tbody style="margin-right:5vw; border-bottom: 1px solid rgb(78,53,36)">
        {% for folio in folio_data %}
        <tr>
          <th scope="row">{{ folio.id }}</th>
          <td>{{ folio.name }}</td>
          <td>{{ folio.email }}</td>
          <td>{{ folio.biography }}</td>
          <td>{{ folio.education }}</td>
          <td>{{ folio.date_of_birth }}</td>
          <td>
            <a href="{{ url_for('folios.view', folio_id=folio.id) }}" class="btn btn-primary" style="width:7vw"><i class="fa-solid fa-magnifying-glass" style="margin-right:5px;"></i>View</a>
            <a href="{{ url_for('folios.update', folio_id=folio.id) }}" class="btn btn-warning" style="width:7vw"><i class="fa-solid fa-pen-to-square" style="margin-right:5px;"></i>Edit</a>
            <a href="{{ url_for('folios.delete', folio_id=folio.id) }}" class="btn btn-danger" style="width:7vw"><i class="fa-solid fa-trash" style="margin-right:5px;"></i>Delete</a>
          </td>
        </tr>
      {% endfor %}
      
        
         

       
      </tbody>
    </table>
    <a href="{{ url_for('folios.create') }}" class="btn btn-primary"><i class="fa-solid fa-file-circle-plus" style="margin-right:1vw;"></i>CREATE DASHBOARD</a>
  </div>
  
</body>
</html>

templates/accounts/login.html
<!DOCTYPE html>
<html>
  <head>
    <title>Login</title>
    <link rel="stylesheet" href="https://kit.fontawesome.com/eab4031eed.css" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/eab4031eed.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </head>
<style>
  .form-signin {
    max-width: 30vw;
    text-align: center;
    position:relative;
    padding-bottom:1vh;
  }

  .form-signin .form-floating:focus-within {
    z-index: 2;
  }

  #grad1 {
    position:relative;
    background-image: linear-gradient(to right, rgb(0,0,205) , rgb(0,255,255));
    color: rgb(78,53,36);
    text-align: center;
    width:100%;
    font-size: 4em;
    padding:2vh;
    letter-spacing: 2vw;
    text-shadow: 2px 2px white;
    font-weight: 900;
  }
  .login-ui {
    height:80vh;
    position:relative;  
    background-color:rgb(78,53,36);    
  }
  .button-gap{
    tyle="position:relative; 
    padding:8vh;
    height:8vh;
    text-align: center;
    width: 100%;
  }
  #under-ui{
    display: grid;
    grid-template-columns: 20vw 25vw auto auto;
    gap: 6vw;
    background-color: rgb(240,248,255);
    padding: 1vw 5vw 1vw 2vw;
  }
  #under-ui div{
  text-align: center;
  padding: 2vh 0;
  font-size: 1.8vh;
  }
  .head-ui{
  padding:10px;
  position:relative;
  padding-right:7vw;
  padding-left:7vw;
  }
  .item{
  padding-top:10px;
  padding-bottom:10px;
  padding-right:3vw;
  padding-left:3vw;
  position:relative;
  text-align: center;
  font-size: 20px;
  color: white;
  text-decoration-line: none;
  }
  a:hover {
  background-color: rgb(160, 110, 73);
  }
  .credit-head{
  font-weight: bold; 
  padding: 1vh 0 ;
  text-align: left;
  }
  .credit-tail{
  padding: 0 0 0 0 ; 
  text-align: left;
  }
  .bar{
  width:100%; 
  height:10vh;
  grid-template-columns: auto;
  display: grid;
  gap: 20px;
  }
  .bar-item{
  width:100%;
  position:relative;
  text-align: left;
  float:none;
  color: white;
  text-decoration-line: none;
  padding:20px;
  }
  .bar-item:hover{
  background-color: rgb(0, 191, 255);
  }
  .offcanvas-title:hover{
  color:rgb(0, 191, 255);
  }
  .center-con {
    display:flex; 
    justify-content: center; 
    align-item:center;
    margin-top:7px;
  }
</style>
<body style="background-color:rgb(240,248,255);">  
  <div class='login-ui'>
    <header>
      <div class="head-ui">
        <div class="offcanvas offcanvas-start" data-bs-scroll="true" tabindex="-1" id="offcanvasWithBothOptions" aria-labelledby="offcanvasWithBothOptionsLabel" 
          style="background-image: linear-gradient(to right, rgb(0,0,205) , rgb(0,255,255)); color: white;">
          <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="offcanvasWithBothOptionsLabel" data-bs-dismiss="offcanvas" aria-label="Close">
            <i class="fa-solid fa-bars" style="margin-right:1vw;"></i>MENU
            </h5>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
          </div>
          <div class="offcanvas-body" style="padding: 0;">
            <div class="bar">
              <a href="/" class="bar-item"><i class="fa-solid fa-house" style="margin-right:1vw;"></i>HOME</a>
              <a href="{{ url_for('accounts.dashboard') }}" class="bar-item"><i class="fa-solid fa-file" style="margin-right:1vw;"></i>DASHBOARD</a>
              <a href="{{ url_for('accounts.login') }}" class="bar-item"><i class="fa-solid fa-right-to-bracket" style="margin-right:1vw;"></i>LOGIN</a>
              <p style="padding:10px;">Please Login or Register to access the website.</p>
            </div> 
          </div>
        </div>
        <a class="item" data-bs-toggle="offcanvas" data-bs-target="#offcanvasWithBothOptions" aria-controls="offcanvasWithBothOptions"> 
          <i class="fa-solid fa-bars" style="margin-right:1vw;"></i>
          MENU
        </a>
        <div style="float: right; ">
          <a class="item"  href="{{ url_for('accounts.login') }}"> <i class="fa-solid fa-right-to-bracket" style="margin-right:1vw;"></i>LOGIN</a>
        </div>
      </div>
    </header>
    <a>
      <h1 id="grad1" >
        <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" class="bi bi-journal-bookmark-fill" viewBox="0 0 16 20" style="margin:2vw; ">
          <path fill-rule="evenodd" d="M6 1h6v7a.5.5 0 0 1-.757.429L9 7.083 6.757 8.43A.5.5 0 0 1 6 8V1z"/>
          <path d="M3 0h10a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2v-1h1v1a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H3a1 1 0 0 0-1 1v1H1V2a2 2 0 0 1 2-2z"/>
          <path d="M1 5v-.5a.5.5 0 0 1 1 0V5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0V8h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0v.5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1z"/>
        </svg>
        FOLIOS
      </h1>
    </a>
    <div style="padding-bottom: 5% ;text-align: center;color: white;" >
      <div class="container" style="position:relative">
        <div class="text-center" >
          <div class="form-signin w-100 m-auto" >
            <form action="{{ url_for('accounts.do_login') }}" method="POST">
              {{ form.hidden_tag() }}
              <h3 class="h3 mb-3 fw-normal">Please sign in</h3>
              <div class= "center-con">
                <div class="form-floating"  style="width:30vw;">
                  <input type="email" class="form-control" id="email" name="email" placeholder="name@example.com" style="border-radius:0.5rem;">
                  <label for="floatingInput" style="color:rgb(105, 105, 105);"><i class="fa-solid fa-user" style="margin-right:1vw; "></i>Email address</label>
                </div>
              </div>
              <div class= "center-con">
                <div class="form-floating"  style="width:30vw;">
                  <input type="password" class="form-control" id="password" name="password" placeholder="Password" style="border-radius:0.5rem;">
                  <label for="floatingPassword" style="color:rgb(105, 105, 105);"><i class="fa-solid fa-key" style="margin-right:1vw;"></i>Password</label>
                </div>
              </div>
              <div class="checkbox mb-3">
                <label>
                <input type="checkbox" value="remember-me"> Remember me
                </label>
              </div>
              <button class="w-100 btn btn-lg btn-primary" type="submit" style="width:30vw;"><i class="fa-solid fa-right-to-bracket" style="margin-right:1vw; "></i>Sign in</button>
            </form>
          </div>
        </div>
      </div>
      <div class='button-gap'>
        <a type="button" class="btn btn-primary btn-lg btn-block" href="{{ url_for('accounts.register') }}" style="position:relative;  width:30vw;">
          <i class="fa-solid fa-user-plus"style="margin-right:0.2vw;">
          </i>
        Register
        </a>
        {% if request.args.get("message") %}
      
        <div class= "center-con">
          <div  class="alert alert-danger" role="alert" style="margin-top:7px; width:30vw; padding:8px 16px; padding-y:0.5rem;padding-x:1rem;font-size:1.25rem;">
            {{ request.args.get("message") }}
          </div>
        </div>
      
          {% endif %}
      </div>
    </div>
  </div>
  <div id="under-ui">
    <div>
      <div style="font-weight: bold; padding: 0 0 2px 0 ; text-align: left;">
        Department of Computer Engineering
      </div>
      <div style="text-align: left;">
          Faculty of Engineering
          Prince of Songkla University
          Hat Yai, Thailand
      </div>
    </div>
    <div>
      <div style="font-weight: bold; padding: 0 0 10px 0 ; text-align: left;">
      Connect Creater
      </div>
        <div style=" padding: 0 0 2px 0 ; text-align: left;">
          <a href="https://www.facebook.com/profile.php?id=100009061745442" style="text-decoration-line: none; background-color: transparent;">
            Facebook
          </a>
        </div>
      <div style=" padding: 0 0 2px 0 ; text-align: left;">
        <a style="pointer-events: none;">
          Email : panpon9988@gmail.com
        </a>
      </div>
    </div>
  </div>
</body>
</html>